Repository dheeraj-2000/dsalgo, pull requests merged in 2022-10, with the labels that each got.

#482 number of dice roll with target sum.cpp
  Recursion/number of dice roll with target sum.cpp
Labels: hacktoberfest-accepted

#484 Hacktoberfest 2022
  Algorithms/Detecting a cycle in a graph (Using three color mechanism).cpp
Labels: hacktoberfest-accepted

#485 Create Search_a_2D_Matrix.cpp
  Algorithms/Search_a_2D_Matrix.cpp
Labels: hacktoberfest-accepted

#487 Added C program
  Binary_Search_Tree/binarytree.c
Labels: hacktoberfest-accepted

#488 Using abs function instead of logical OR in (22)
  CODECHEF EASY/ALTER.cpp
Labels: hacktoberfest-accepted

#490 giving file extension
  Algorithms/#include <bits/TravellingSalesmanProblem.cpp
Labels: hacktoberfest-accepted

#492 Added Heap_Sort.java
  Sort/Heap_Sort.java
Labels: hacktoberfest-accepted

#493 Create mergesort.java
  Algorithms/mergesort.java
Labels: hacktoberfest-accepted

#494 added merge sorted arrays code in python
  Leetcode problems/merge_sorted_arrays.py
Labels: hacktoberfest-accepted

#495 Added Binary Search implemenation for java
  Searching algos/BinarySearch.java
Labels: hacktoberfest-accepted

#497 Best_Time_To_Buy_Stocks.cpp
  Arrays/Best_Time_To_Buy_Stocks.cpp
Labels: hacktoberfest-accepted

#504 Create Linked_List_Cycle.cpp
  Linked_List/Linked_List_Cycle.cpp
Labels: hacktoberfest-accepted

#505 Create best_time_to_buy_sell_stock.cpp
  Top Interview Questions/Interview_Questions/best_time_to_buy_sell_stock.cpp
Labels: hacktoberfest-accepted

#506 Create next_permutation.cpp
  Arrays/next_permutation.cpp
Labels: hacktoberfest-accepted

#507 Create pairSum.cpp
  Arrays/pairSum.cpp
Labels: hacktoberfest-accepted

#508 Create reverse_list_in_k_groups.cpp
  Linked_List/reverse_list_in_k_groups.cpp
Labels: hacktoberfest-accepted

#509 Add files via upload
  Algorithms/Aggressivecows(Binarysearch).cpp
Labels: hacktoberfest-accepted

#510 8_queens_problem
  8_queens_problem.cpp
Labels: hacktoberfest-accepted

#516 Added RotateList Program
  Leetcode problems/69.RotateList.cpp
Labels: hacktoberfest-accepted

#519 I got uh bruh! added your credit name at footer as your legacy
  README.md
Labels: hacktoberfest-accepted

#521 Create Sort-0-1-2.cpp
  Arrays/Sort-0-1-2.cpp
Labels: hacktoberfest-accepted

#522 136 LeetCode single number problem python #Hacktoberfest
  Leetcode problems/single_number.py
Labels: hacktoberfest-accepted

#525 Added Factorial using recursion in python
  Recursion/factorial_using_recursion.py
Labels: hacktoberfest-accepted

#526 2342. Max Sum of a Pair With Equal Sum of Digits
  Leetcode problems/2342. Max Sum of a Pair With Equal Sum of Digits.cpp
Labels: hacktoberfest-accepted

#527 added binary search algorithm in java
  Searching algos/binarySearch.java
Labels: hacktoberfest-accepted

#529 added bitwise Operators
  bitwiseOperators/Find_ith_bit.java
  bitwiseOperators/OddEven.java
  bitwiseOperators/SwapNumbers.java
  bitwiseOperators/binarys1sCompliment.java
Labels: hacktoberfest-accepted

#531 max_subarray_sum in js format
  Arrays/max_subarray_sum.js
Labels: hacktoberfest-accepted

#537 Add files via upload
  Arrays/Moore_Voting_Algorithm.cpp
Labels: hacktoberfest-accepted

#539 abdul karim dsalgo
  Algorithms/variable/ChangesVariable.kt
Labels: change requested

#541 Added quick_sort.py algorithm file
  Algorithms/quick_sort.py
Labels: hacktoberfest-accepted

#543 Adding Longest Increasing Path in Matrix correctly
  DP/Longest Increasing Path in Matrix/329-LongestIncreasingPathInMatrix.java
  DP/LongestIncreasingPathInMatrix Leetcode329
Labels: hacktoberfest-accepted

#552 Add identical tree
  Trees/identicalTree.cpp
Labels: hacktoberfest-accepted

#554 Create SpiralMatrix.java
  Arrays/SpiralMatrix.java
Labels: hacktoberfest-accepted

#555 regression.py
  Algorithms/linearreg.py
  Algorithms/multiplereg.py
Labels: hacktoberfest-accepted

#558 Create saddlePoint.java
  Arrays/saddlePoint.java
Labels: hacktoberfest-accepted

#562 Create Merge_Sort.py
  Algorithms/Merge_Sort.py
Labels: hacktoberfest-accepted

#563 Creating TwoSum
  Arrays/TwoSum.java
Labels: hacktoberfest-accepted

#566 Modified and added proper bubble sort code in java
  Sort/bubble__sort.java
  Sort/bubble_sort.java
Labels: hacktoberfest-accepted

#567 Create maxArea.py
  Graph/Graph_Valid_Tree.py
  Graph/maxArea.py
Labels: hacktoberfest-accepted

#570 Create LongestIncreasingSubseq.java Leetcode
  Leetcode problems/LongestIncreasingSubseq.java
Labels: hacktoberfest-accepted

#571 Create Dijkstra_spf.cpp
  Algorithms/Dijkstra_spf.cpp
Labels: hacktoberfest-accepted

#572 Added BFS Algorithm please check it
  Algorithms/Breadth First Search.cpp
Labels: hacktoberfest-accepted

#573 Strassens algorithm in C
  Algorithms/Strassensalgo.c
Labels: hacktoberfest-accepted

#574 Create valid-anagram.js
  Leetcode problems/valid-anagram.js
Labels: hacktoberfest-accepted

#577 Added Leetcode Problem Decode Ways in CPP
  Leetcode problems/Decode Ways.cpp
Labels: hacktoberfest-accepted

#578 Add Permuations With Case change (LetterCasePermutation.cpp)
  Recursion/LetterCasePermutation.cpp
Labels: hacktoberfest-accepted

#579 #575 . Added solution to CodeForces problem #719-A in JAVA.
  CodeForces Problems/DoNotBeDistracted.java
Labels: hacktoberfest-accepted

#581 Create bubblesort.java
  bubblesort.java
Labels: hacktoberfest-accepted

#584 Add files via upload
  Leetcode problems/4. Median of Two Sorted Arrays.java
Labels: hacktoberfest-accepted

#589 Create rotting_oranges.cpp
  Graph/rotting_oranges.cpp
Labels: hacktoberfest-accepted

#595 Create My _Calendar_III.cpp
  Leetcode problems/My _Calendar_III.cpp
Labels: hacktoberfest-accepted

#609 Kadane's Algorithm
  Algorithms/Graph/.cph/.Kadane's_algorithm.cpp_1d25845e7d2ec1b81fac4c8baeb39b9b.prob
  Algorithms/Graph/Kadane's_algorithm.bin
  Algorithms/Graph/Kadane's_algorithm.cpp
Labels: hacktoberfest-accepted

#611 Minimum_Multiplications_to_Reach_End.cpp
  DP/Minimum_Multiplications_to_Reach_End.cpp
Labels: hacktoberfest-accepted

#613 Bellman for in python
  Graph/Bellman-Ford Algorithm/bellmanford.py
Labels: hacktoberfest-accepted

#619 Create Linear_Search.java
  Searching algos/Linear_Search.java
Labels: hacktoberfest-accepted

#621 Order Agnostic Binary Search
  Searching algos/Order_Agnostic_Binary_Search.java
Labels: hacktoberfest-accepted

#623 Update README.md
  README.md
Labels: hacktoberfest-accepted

#624 Added code for Maximum Score from Performing Multiplication Operations
  DP/Maximum_Score_From_performing_Multiplication.java
Labels: hacktoberfest-accepted

#625 Euclid's Algorithm
  array/Euclid's Algo
Labels: hacktoberfest-accepted

#628 Create XORIER.cpp
  CODECHEF EASY/XORIER.cpp
Labels: hacktoberfest-accepted

#631 Adding sorting a queue program in Queue section
  Queue/sort_queue.cpp
Labels: Hacktoberfest22

#633 Added Javalinkedlist folder
  Linked_List/javalinkedlist/Solution.class
  Linked_List/javalinkedlist/closestPrime.class
  Linked_List/javalinkedlist/closestPrime.java
Labels: Hacktoberfest22

#638 DP- Palindrome Partitioning II added
  DP/Palindrome Partitioning II.java
  DP/Palindrome Partitioning II/palindrome partioning 2.java
  Graph/Is Graph Cyclic.java
  Linked_List/K-Reverse in LinkedList.java
  Recursion/N-Queens_problem.java
Labels: hacktoberfest-accepted, Hacktoberfest22

#639 Create Count_Sort.py
  Sort/Count_Sort.py
Labels: hacktoberfest-accepted

#646 createed subset java code
  Leetcode problems/Subset.java
Labels: hacktoberfest-accepted

#651 added Sieve Of Eratosthenes
  Algorithms/SieveOfEratosthenes.cpp
Labels: hacktoberfest-accepted

#655 create RBTrees.cpp
  Trees/RBTrees.cpp
Labels: hacktoberfest-accepted

#659 Add files via upload
  DP/boolean-parenthesization-problem.cpp
Labels: hacktoberfest-accepted

#660 Create 237-Delete Node in a Linked List.java
  Leetcode problems/237-Delete Node in a Linked List.java
Labels: hacktoberfest-accepted

#661 Create 237-Delete Node in a Linked List.cpp
  Leetcode problems/237-Delete Node in a Linked List.cpp
Labels: hacktoberfest-accepted

#666 Create Check_Repeated_digits_using_arrays.cpp
  Arrays/Check_Repeated_digits_using_arrays.cpp
Labels: hacktoberfest-accepted

#667 Adding the Median algorithm Python Code
  Algorithms/median_algorithm.py
Labels: hacktoberfest-accepted

#669 Create Iterative_Postorder_Traversal.java
  Binary_tree/Iterative_Postorder_Traversal.java
Labels: hacktoberfest-accepted

#670 2416_Sum of Prefix Scores of Strings
  Leetcode problems/2416-Sum of Prefix Scores of Strings.java
Labels: hacktoberfest-accepted

#671 Added activity selection problem
  DP/activity_selection.cpp
Labels: hacktoberfest-accepted

#673 create QuickSort.c
  Sort/QuickSort.c
Labels: hacktoberfest-accepted

#674 create MergeSort.c
  Sort/MergeSort.c
Labels: hacktoberfest-accepted

#675 added leetcode solutions
  Leetcode problems/403.FrogJump.cpp
  Leetcode problems/416.PartitionEqualSubsetSum.cpp
  Leetcode problems/583.DeleteOperationForTwoStrings.cpp
Labels: hacktoberfest-accepted

#676 added new magical chess board problem
  Arrays/magical_chessboard.cpp
Labels: hacktoberfest-accepted

#678 Sort the linked list in ascending order
  Algorithms/#include <bits/TravellingSalesmanProblem.cpp
  Leetcode problems/148. Sort List.cpp
Labels: hacktoberfest-accepted

#680 Create multiple_sort_menu_driven.cpp
  Sort/multiple_sort_menu_driven.cpp
Labels: hacktoberfest-accepted

#681 added linked list loop detection
  Leetcode problems/Detect loop in linked list_ayush91985.cpp
Labels: hacktoberfest-accepted

#682 subarray_with_given_sum.java
  Arrays/subarray_with_given_sum.java
Labels: hacktoberfest-accepted
